image: node:14

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
pages: 
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run lint
    - npm run deobfuscate-resources
    - npm run build
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
    - master

cfworker:
  stage: deploy
  script:
    - npm install @cloudflare/wrangler
    - sed -i "s/\!AccountID/$CF_AID/g" wrangler.toml
    - sed -i "s/\!ZoneID/$CF_ZID/g" wrangler.toml
    - npx wrangler publish
  only:
    - master
